demo/urls.py
from django.contrib import admin
from demo_app import views
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("demo_app.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

demo_app/urls.py
from django.urls import path
from demo_app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home, name="home"),
    path("database/", views.database, name="database"),
    path("login/", auth_views.LoginView.as_view(template_name="demo_app/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
    path("signup/", views.signup, name="signup"),
]

demo_app/models.py
from django.db import models

class Transmission(models.TextChoices):
    AUTO = 'AUTO', 'Automatic'
    MANUAL = 'MANUAL', 'Manual'

class Cars(models.Model):
    full_name = models.CharField(max_length=100, blank=False)
    brand = models.CharField(max_length=40)
    door_num = models.IntegerField()
    transmission = models.CharField(
        max_length=10,
        choices = Transmission.choices,
        default=Transmission.AUTO
    )
    price = models.DecimalField(decimal_places=2, max_digits=999)

    def __str__(self):
        return f"{self.full_name}"

demo_app/forms.py
from django import forms
from demo_app.models import Cars
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CarsForm(forms.ModelForm):
    class Meta:
        model = Cars
        fields = "__all__"   # NOTE: the trailing comma is required

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2") #Django has built in password confirmation, password2 is not stored, only used for confirmation

demo_app/views.py
from django.shortcuts import redirect, render
from demo_app.forms import CarsForm
from demo_app.models import Cars
from .forms import SignUpForm

def home(request):
    return render(request, "demo_app/home.html")

def database(request):
    #Filtering
    query = request.GET.get("search", "")
    form = CarsForm(request.POST or None) # this fetches the form from CarsForm
    cars = Cars.objects.all()
    cars_filtered = Cars.objects.filter(full_name__icontains=query) if query else None
    if request.method == "POST":
        if form.is_valid():
            message = form.save(commit=False)
            message.save()
            return redirect("database")
    else:
        return render(request, "demo_app/databases.html", {
            "form":form,
            "cars":cars,
            "search":query,
            "cars_filtered":cars_filtered}) # here the destination template is chosen and the context of the form and Cars model are passed in so data can be read 

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("login")
    else:
        form = SignUpForm()
    return render(request, "demo_app/signup.html", {"form": form})

demo_app/templates/demo_app/cars_input_form.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>

demo_app/templates/demo_app/cars_search_fields.html
<form method="get" action="">
    <a>Full Name </a><input type="text" name="search" value="{{ search }}" placeholder="Search cars...">
    <button type="submit">Search</button>
</form>

demo_app/templates/demo_app/cars_table.html
<h2>All Cars</h2>
<table class="cars_table">
    <tr>
        <th>Full Name</th>
        <th>Brand</th>
        <th>Doors</th>
        <th>Transmission</th>
        <th>Price</th>
    </tr>
    {% for car in cars %}
    <tr>
        <td>{{ car.full_name }}</td>
        <td>{{ car.brand }}</td>
        <td>{{ car.door_num }}</td>
        <td>{{ car.get_transmission_display }}</td>
        <td>{{ car.price }}</td>
    </tr>
    {% empty %}
    <tr><td colspan="5">No cars found.</td></tr>
    {% endfor %}
</table>

demo_app/templates/demo_app/cars_table_filter.html
<table class="cars_table">
    <tr>
        <th>Full Name</th>
        <th>Brand</th>
        <th>Doors</th>
        <th>Transmission</th>
        <th>Price</th>
    </tr>
    {% for car in cars_filtered %}
    <tr>
        <td>{{ car.full_name }}</td>
        <td>{{ car.brand }}</td>
        <td>{{ car.door_num }}</td>
        <td>{{ car.get_transmission_display }}</td>
        <td>{{ car.price }}</td>
    </tr>
    {% empty %}
    <tr><td colspan="5">No cars found, try entering a different search criteria</td></tr>
    {% endfor %}
</table>

demo_app/templates/demo_app/databases.html
{% extends "demo_app/layout.html" %}
{% block title %}
Database Demo
{% endblock %}
{% block content %}
This is a demonstration of a simple database of cars, the form can be used to create new entries in to the database. This should show up in the table below immediately as it is showing all records
{% include "demo_app/cars_input_form.html" %}
<h2>All Cars</h2>
{% include "demo_app/cars_table.html" %}
{% if user.is_authenticated %}
    <h2>Filtered Cars Table</h2>
    {% include "demo_app/cars_search_fields.html" %}
    {% include "demo_app/cars_table_filter.html" %}
{% endif %}
{% endblock %}

demo_app/templates/demo_app/home.html
{% extends "demo_app/layout.html" %}
{% block title %}
Python Django Tech Demo
{% endblock %}
{% block content %}
<p>Welcome to my tech demo of Python Django, some features are only accessible when logged in, feel free to create a user. Do not use any real emails/usernames/passwords!</p>
{% endblock %}

demo_app/templates/demo_app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'demo_app/site.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
</head>

<body>
<div class="navbar">
    <div class="navbar-left">
        <a href="{% url 'home' %}" class="navbar-brand">Home</a>
        <a href="{% url 'database' %}" class="navbar-brand">Database</a>
    </div>
    <div class="navbar-right">
        {% if user.is_authenticated %}
            <a class="navbar-brand">Welcome, {{ user.username }}! </a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Log Out</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}?next={{ request.path }}" class="navbar-brand">Login</a> <!-- The next = {{ request.path }} captures the path the request to login was made from, the next is then used to return the user to where they came from -->
            <a href="{% url 'signup' %}" class="navbar-brand">Sign Up</a>
        {% endif %}
    </div>
</div>

<div class="body-content">
    {% block content %}
    {% endblock %}
    <hr/>
</div>
</body>
</html>

demo_app/templates/demo_app/login.html
{% extends "demo_app/layout.html" %}
{% block title %}
Login
{% endblock %}
{% block content %}
<form method="post">
<!-- the .as_p call puts the form into <p> tags automatically -->
  {% csrf_token %}
  {{ form.as_p }}
  <input type="hidden" name="next" value="{{ next|default:'/' }}"><!--- next here is used by django framework to redirect the user-->
  <button type="submit">Submit</button>
</form>
{% endblock %}

demo_app/templates/demo_app/signup.html
{% extends "demo_app/layout.html" %}
{% block title %}
{% endblock %}
{% block content %}
<!-- TODO format this to look better -->
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock %}